# 제2강 실습 문제 풀이

## 1. 실습 문제: 시험 점수 처리 (Operation with Test Scores)
학생 5명(Tanya, Manual, Adwoa, Jeremy, Cody)의 세 차례 시험 점수 데이터를 활용해 NumPy 배열 연산을 실습합니다.

In [3]:
import numpy as np

# [1단계] 배열 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

print(test_1)
print(test_2)
print(test_3)

[92 94 88 91 87]
[ 79 100  86  93  91]
[87 85 72 90 92]


In [4]:
# [2단계] 배열 연산 (Broadcasting) - 세 번째 시험 점수에 각각 +2점

test_3_fixed = test_3 + 2

test_3_fixed

array([89, 87, 74, 92, 94])

In [5]:
test_3 = test_3 + 2

test_3

array([89, 87, 74, 92, 94])

In [6]:
total_grade = test_1 + test_2 + test_3_fixed

total_grade

array([260, 281, 248, 276, 272])

In [7]:
final_grade = total_grade / 3

final_grade

array([86.66666667, 93.66666667, 82.66666667, 92.        , 90.66666667])

In [8]:
jeremy_test_2 = test_2[3]

jeremy_test_2

np.int64(93)

In [11]:
manual_adwoa_test_1 = test_1[1:3] #[1:stop-1]

manual_adwoa_test_1

array([94, 88])

In [12]:
student_scores = np.array([test_1, test_2, test_3_fixed])

student_scores

array([[ 92,  94,  88,  91,  87],
       [ 79, 100,  86,  93,  91],
       [ 89,  87,  74,  92,  94]])

In [13]:
student_scores[2, 0]

np.int64(89)

In [14]:
student_scores[0:3, 4]

array([87, 91, 94])

In [15]:
student_scores[:3, 4]

array([87, 91, 94])

# 골디락스 포리지 페스티벌

In [16]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

porridge

array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

In [19]:
cold = porridge[porridge < 60]
hot = porridge[porridge > 80]
just_right = porridge[(porridge >= 60) & (porridge <= 80)]

print(cold)
print(hot)
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]


In [24]:
np.random.seed(0)

arr1= np.random.randint(10, size=6)
arr2= np.random.randint(10, size=(3,4))
arr3= np.random.randint(10, size=(3,4,5))

# print(arr1)
# print(arr2)
print(arr3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [27]:
arr = np.arange(10) # arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[3:7]

array([3, 4, 5, 6])

In [30]:
arr[:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[5:]

array([5, 6, 7, 8, 9])

In [32]:
arr[::3]

array([0, 3, 6, 9])

In [33]:
arr[2:8:2]

array([2, 4, 6])

In [34]:
# 난수 배열 생성
np.random.seed(0) 
arr = np.random.randint(10, size=(6, 8)) 

arr

array([[5, 0, 3, 3, 7, 9, 3, 5],
       [2, 4, 7, 6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7]], dtype=int32)

In [35]:
arr[:2, :3]

array([[5, 0, 3],
       [2, 4, 7]], dtype=int32)

In [36]:
arr[:3, ::2]

array([[5, 3, 7, 3],
       [2, 7, 8, 1],
       [7, 8, 5, 8]], dtype=int32)

In [37]:
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [38]:
np.sum(arr, axis=0)

array([14, 13, 13, 14])

In [39]:
np.sum(arr, axis=1)

array([11, 24, 19])

In [2]:
import numpy as np

arr = np.array([1, 2, 3])

In [3]:
prices_arr = np.array(arr)

prices_arr += 5

prices_arr

array([6, 7, 8])

In [4]:
np.arange(3)

array([0, 1, 2])

In [9]:
np.random.seed(0)
arr = np.random.randint(10, size=(3,4))
arr_3 = np.random.randint(10, size=(3,4,5))

arr_3

array([[[8, 8, 1, 6, 7],
        [7, 8, 1, 5, 9],
        [8, 9, 4, 3, 0],
        [3, 5, 0, 2, 3]],

       [[8, 1, 3, 3, 3],
        [7, 0, 1, 9, 9],
        [0, 4, 7, 3, 2],
        [7, 2, 0, 0, 4]],

       [[5, 5, 6, 8, 4],
        [1, 4, 9, 8, 1],
        [1, 7, 9, 9, 3],
        [6, 7, 2, 0, 3]]], dtype=int32)

In [10]:
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [11]:
arr_sub = arr[:2, :2]

arr_sub

array([[5, 0],
       [7, 9]], dtype=int32)

In [12]:
arr_sub[0,0] = 99

In [13]:
arr_sub

array([[99,  0],
       [ 7,  9]], dtype=int32)

In [15]:
arr[0,0]

np.int32(99)

In [18]:
arr_sub = arr[:2, :2].copy()

arr_sub

array([[99,  0],
       [ 7,  9]], dtype=int32)

In [19]:
arr_sub[0, 1] = 99

In [20]:
arr_sub

array([[99, 99],
       [ 7,  9]], dtype=int32)

In [21]:
arr

array([[99,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]], dtype=int32)

In [22]:
arr = np.arange(6)

In [23]:
arr

array([0, 1, 2, 3, 4, 5])

In [24]:
grid = arr.reshape(2, 3)

grid

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
arr = np.array([[1, 2], [3, 4]])

arr_1 = arr.reshape(-1)

arr_2 = arr.reshape(4,)

arr_1
arr_2

array([1, 2, 3, 4])

In [32]:
arr = np.array([[1, 2], [3, 4]])

In [33]:
arr_2 = arr.reshape(4,)

arr_2

array([1, 2, 3, 4])

In [34]:
import pandas as pd

# 시험에 나올 만한 예시 데이터프레임 생성
# 인덱스를 일부러 숫자가 아닌 'a', 'b', 'c', 'd'라는 명시적 문자열로 지정했어.
data = {
    'name': ['Tanya', 'Manual', 'Adwoa', 'John'],
    'score': [92, 94, 88, 75]
}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])

print("--- 원본 데이터프레임 ---")
print(df)

--- 원본 데이터프레임 ---
     name  score
a   Tanya     92
b  Manual     94
c   Adwoa     88
d    John     75
